//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramlama.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImdbEntities : DbContext
    {
        public ImdbEntities()
            : base("name=ImdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FilmTur> FilmTur { get; set; }
        public virtual DbSet<Galeri> Galeri { get; set; }
        public virtual DbSet<OyuncuFilm> OyuncuFilm { get; set; }
        public virtual DbSet<TurTip> TurTip { get; set; }
        public virtual DbSet<Uyruk> Uyruk { get; set; }
        public virtual DbSet<Oyuncu> Oyuncu { get; set; }
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Uyelik> Uyelik { get; set; }
    }
}
