//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramlama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OyuncuFilm
    {
        public int OyuncuFilmID { get; set; }
        public int OyuncuID { get; set; }
        public int FilmID { get; set; }
    
        public virtual Oyuncu Oyuncu { get; set; }
        public virtual Film Film { get; set; }
    }
}
