//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramlama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oyuncu
    {
        public Oyuncu()
        {
            this.OyuncuFilm = new HashSet<OyuncuFilm>();
        }
    
        public int OyuncuID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<System.DateTime> OlumTarihi { get; set; }
        public int UyrukID { get; set; }
        public string Biyografi { get; set; }
        public byte[] Fotograf { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
    
        public virtual Uyruk Uyruk { get; set; }
        public virtual ICollection<OyuncuFilm> OyuncuFilm { get; set; }
    }
}
