//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramlama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurTip
    {
        public TurTip()
        {
            this.FilmTur = new HashSet<FilmTur>();
        }
    
        public int TurTipID { get; set; }
        public string Ad { get; set; }
    
        public virtual ICollection<FilmTur> FilmTur { get; set; }
    }
}
