//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramlama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyruk
    {
        public Uyruk()
        {
            this.Oyuncu = new HashSet<Oyuncu>();
        }
    
        public int UyrukID { get; set; }
        public string Ad { get; set; }
    
        public virtual ICollection<Oyuncu> Oyuncu { get; set; }
    }
}
